import { Link } from "react-router";
const TermsAndConditions = () => {
  return (
    <div className="max-w-4xl mx-auto p-6 space-grotesk">
      <h1 className="text-3xl font-bold mb-6 bai-jamjuree-bold">
        Terms of Service
      </h1>

      <div className="space-y-6">
        <section>
          <h2 className="text-xl font-semibold mb-3 bai-jamjuree-semibold">
            1. Acceptance of Terms
          </h2>
          <p>
            By using AntiNode, you agree to these terms. If you disagree, please
            don't use our service.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3 bai-jamjuree-semibold">
            2. Service Description
          </h2>
          <p>
            We provide AI-powered query services with daily limits, limited
            number of chatrooms and dashboard analytics for free users and
            unlimited access of all services for premium users.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3 bai-jamjuree-semibold">
            3. User Responsibilities
          </h2>
          <ul className="list-disc pl-6 space-y-2">
            <li>Don't abuse our API or attempt to circumvent rate limits</li>
            <li>Don't use our service for illegal activities</li>
            <li>Don't attempt to reverse engineer our platform</li>
            <li>
              The AntiNodeSdk for plug and use document and general information
              based AI systems is currently in beta stage and open source you
              can access it from our{" "}
              <a
                href="https://github.com/Ayushgairola6/AntiNodek"
                className="text-green-500"
              >
                github repo
              </a>{" "}
              and feel free to modify it for your own use case.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3 bai-jamjuree-semibold">
            4. Payments & Refunds
          </h2>
          <p>
            Premium subscriptions are billed through Paddle. Refunds are handled
            according to our Refund Policy.
          </p>
          <Link
            to="/Refund-Policy"
            className="bai-jamjuree-regular text-blue-600 text-sm"
          >
            View refund policy
          </Link>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3 bai-jamjuree-semibold">
            5. Limitation of Liability
          </h2>
          <p className="space-grotesk">
            We provide service as a Sass , all the response generated by the
            models are solely based on information from community contributions,
            internet information and your private documents . No pre trained
            data is used to answer your questions to prevent hallucinations and
            risk of misinformation, but we still recommend double checking any
            information you get.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3 bai-jamjuree-semibold">
            6. Changes to Terms
          </h2>
          <p>
            We may update these terms in future. Continued use means you accept
            the changes.
          </p>
        </section>
      </div>
    </div>
  );
};
export default TermsAndConditions;
