import { supabase } from "../controllers/supabaseHandler.js";
import { extractUUID } from "./phase2_action.js";

//gets the basic information related the document from the database or cache if available
export async function ProcessDocumentInfoGathering(ReferenceArray, user) {
  const Document_Information = [];
  if (ReferenceArray.length > 0) {
    // Execute all doc fetches in parallel
    await Promise.all(
      ReferenceArray.map(async (req) => {
        const docId = req.arguments.doc_id;
        if (docId) {
          try {
            // Assuming config.execute returns { metadata: {...} }
            const result = await req.config.execute(docId, user);
            if (result) {
              Document_Information.push({
                doc_id: docId,
                result,
              }); //with the document_id identifier
            }
          } catch (e) {
            console.error(`Failed to fetch doc ${docId}`, e);
          }
        }
      })
    );
  }
  return Document_Information;
}

//gets the conttext from public contributions
export async function ProcessKnowledgeBaseContextGathering(
  ReferenceArray,
  user,
  MetaDataArray
) {
  const Response = [];
  if (ReferenceArray.length > 0) {
    let i = 0;

    await Promise.all(
      ReferenceArray.map(async (req) => {
        try {
          //find the category-subCategory-description of the document from the metadat
          const current = MetaDataArray.find(
            (func) => func.doc_id === extractUUID(req?.arguments?.query) //if the query has the uuid of any document
          );
          let results;
          if (current) {
            results = await req.config.execute(
              current.result.metadata.category || "General",
              current.result.metadata.subCategory || "General",
              current.result.metadata.about,
              user
            );
          }
          //find fetch based on the metadata of other documents
          else if (MetaDataArray.length > 0) {
            let i = 0;
            while (i < MetaDataArray.length) {
              results = results = await req.config.execute(
                MetaDataArray[i].result.metadata.category || "General",
                MetaDataArray[i].result.metadata.subCategory || "General",
                MetaDataArray[i].result.metadata.about,
                user
              );
              i++;
            }
          }
          if (results) {
            Response.push({
              category: current.result.metadata.category,
              subcategory: current.result.metadata.subCategory,
              text: results,
            });
          }

          // console.log(result);
        } catch (error) {
          console.error(
            error,
            "error while fetching info from public sources helper_functions line:82"
          );
        }
      })
    );
  }

  return Response;
}

//helped function to process web results
export async function ProcessWebContextGathering(
  ReferenceArray,
  user,
  documentInfoArray
) {
  const FinalResult = [];
  let AllFavicons = [];
  try {
    // Process all function calls (requests) in parallel
    await Promise.all(
      ReferenceArray.map(async (req) => {
        const rawQuery = req.arguments.query.trim();
        const lowerQuery = rawQuery.toLowerCase();

        // --- SCENARIO 1: Context-Dependent Query ("AUTO" or Mixed) ---
        if (lowerQuery.includes("auto")) {
          // EDGE CASE: User asks for "AUTO" search but has no documents open
          if (!documentInfoArray || documentInfoArray.length === 0) {
            return; // Skip execution
          }

          // We iterate through documents ONLY here when we do not have a query
          for (const doc of documentInfoArray) {
            // Safe extraction of metadata (fallback to title if 'about' is missing)
            const metaContext =
              doc.result?.metadata?.about || doc.result?.metadata?.title || "";

            if (!metaContext) continue; // Skip if no usable context found

            let finalQuery = "";

            if (lowerQuery === "auto") {
              // Exact replacement
              finalQuery = metaContext;
            } else {
              // Hybrid replacement (e.g., "History of AUTO")
              // Uses regex to replace 'auto' (case insensitive) with context
              finalQuery = rawQuery.replace(/auto/gi, metaContext);
            }

            const result = await req.config.execute(finalQuery, user);
            AllFavicons = [...result.favicons];
            FinalResult.push({
              query: finalQuery, // Store the actually executed query
              originalDocId: doc.result.doc_id || null, // useful for tracking
              webResults: result.FormattedResults,
            });
          }
        }

        // --- SCENARIO 2: Explicit Query (Normal Search) --- when generated by model
        else {
          const result = await req.config.execute(rawQuery, user);
          AllFavicons = [...result.favicons];
          FinalResult.push({
            query: rawQuery,
            webResults: result.FormattedResults,
          });
        }
      })
    );

    return { FinalResult, AllFavicons };
  } catch (error) {
    console.error("Web Context Error:", error);
    return []; // Return empty array instead of string for consistency
  }
}
//checking the private document information of the user
export async function CheckPrivateDocs(ReferenceArray, user, DocumentArray) {
  const FinalResult = [];
  await Promise.all(
    ReferenceArray.map(async (req) => {
      const document_id = req.arguments.doc_id;

      if (document_id && document_id !== "AUTO") {
        const documentQuery = DocumentArray.find(
          (func) => func.doc_id === document_id
        );
        // console.log(DocumentArray);
        const result = await req.config.execute(
          document_id,
          documentQuery.result?.metadata?.about,
          user
        ); //user file description as query
        FinalResult.push({ document_id: document_id, context: result });
      } else {
        const documentQuery = DocumentArray.find(
          (func) => func.doc_id !== document_id
        );

        const result = await req.config.execute(
          document_id,
          documentQuery.result.about,
          user
        ); //user file description as query
        FinalResult.push({ document_id: document_id, context: result });
      }
    })
  );
  return FinalResult;
}

//storing any memories for the user
export async function HandleMemoryStorage(user, ReferenceArray) {}

//retrieving any memories
export async function RetrieveMemories(user, ReferenceArray) {}

//fetch last few messages for reminder whwer we left off
export async function FetchPastMessagesFromDbAndCacheThem(user) {
  const limit = user.PaymentStatus === false ? 5 : 10;
  const { data, error } = await supabase
    .from("Conversation_History")
    .select("created_at,question,AI_response")
    .eq("user_id", user.user_id)
    .limit(limit)
    .order("created_at", { ascending: false });

  if (data?.length === 0 || error) {
    return { message: "There is no past conversation history of this user" };
  }

  return data;
}

//summary extractor for room memory
export async function ExtractChatsSummary(
  ReferenceArray,
  room_id,
  user_question
) {
  await Promise.all(
    ReferenceArray.map(async (req) => {
      const query = req.arguments.query;
      if (query) {
        const result = await req.config.execute(
          query ? query : user_question,
          room_id
        ); //u
      }

      return result;
    })
  );
}

export async function RetrieveInformatioByName(ReferenceArray, user) {
  const Document_Information = [];

  if (ReferenceArray.length > 0) {
    // Execute all doc fetches in parallel
    await Promise.all(
      ReferenceArray.map(async (req) => {
        const filename = req?.arguments?.filename;
        //if there is a file name and the file name is of string type and filename is not auto
        if (
          filename &&
          typeof filename === "string" &&
          filename.toLowerCase() !== "auto"
        ) {
          try {
            // Assuming config.execute returns { metadata: {...} }
            const result = await req.config.execute(filename, user);

            if (result) {
              Document_Information.push(result); //with the document_id identifier
            }
          } catch (e) {
            console.error(`Failed to fetch doc ${filename}`, e);
          }
        }
      })
    );
  }
  return Document_Information;
}
