import { genAI } from '../controllers/ModelController.js'
import { notifyMe } from '../ErrorNotificationHandler/telegramHandler.js'
import { SearchQueryResults, formatForGemini } from '../OnlineSearchHandler/WebSearchHandler.js'
import dotenv from 'dotenv';
dotenv.config();


//function to identify the functions needed to process the request
export async function IdentifyRequestInputs(req, res) {
  const user = req.user;
  if (!user) {
    return res.status(401).send({ message: "Please log in to continue" });
  }

  const { question, MessageId, userMessageId } = req.body;

  console.log(req.body)
  if (!question || typeof question !== 'string' || !MessageId || typeof MessageId !== 'string' || !userMessageId || typeof userMessageId !== 'string') {
    return res.status(400).send({ message: "Invalid data has been sent to the server" });
  }

  try {
    let FinalString = `${process.env.IdentifierPrompt}_This is the users question=${question}`//command for the model

    const EstimattedTokens = await genAI.models.countTokens({
      model: "gemini-2.5-flash-lite",//for low token consumption and fast results
      contents: FinalString,
    });
    console.log(EstimattedTokens, 'token used to process the request')

    const responseText = FinalString;
    // const result = await genAI.models.generateContent({
    //   model: "gemini-2.5-flash-lite",
    //   contents: [{ role: "user", parts: [{ text: FinalString }] }],
    //   generationConfig: {
    //     temperature: 0.4,
    //     topP: 0.95,
    //     topK: 40,
    //     maxOutputTokens: 100,///maximum 300 characters output
    //   },
    // });

    // const responseText = result.text;
    // if (!responseText) {
    //   await notifyMe(
    //     `Error while generating a response , the code execution results are these`,
    //     JSON.stringify(result.codeExecutionResult)
    //   );
    //   return { error: "The server is very busy , please try again !" };
    // }
    console.log(responseText, 'the response generated by the model')
    // return { error: "Testing out the error fallback function" };
    return res.send({
      Answer: responseText,
      message: "Results found",
      // favicon: FormattedFavicon | [],
    });
  } catch (SynthesisError) {
    await notifyMe('An error occured in the synthesis hanlder', SynthesisError)
  }
}

// function to process the request
const FunctionLists = [{ name: "get_memory", method: getMemory() }, { name: "store_memory", method: storeMemory() }, { name: "search_knowledge", method: searchKnowledge() }, { name: "ask_private", method: askPrivate }, { name: "search_web", method: searchWeb }]; //currently allowed method


//central funciton that will process the request based on the functionname
function CentralFunctionProcessor(functionName, args) {
  if (!functionName || typeof functionName !== 'string' || !FunctionLists.includes(functionName) || !args) {
    console.warn(args)
    return { message: "Invalid arguments all the information is needed to process the request" };
  }

  //will append the  resulst to this string for final context
  //invoking the functions based on the functions name


  return;
}

//retrive memory from the neo4j instance 
function getMemory(args) {

}
function storeMemory(args) {

}
function searchKnowledge(args) {

}
function askPrivate(args) {

}
async function searchWeb(args) {
  const question = args.question
  if (!question || typeof question !== 'string') {
    return { message: "The question was invalid" };
  }

  const webresults = await SearchQueryResults(question);
  if (webresults.error) {
    return { message: "The question was invalid" };
  }

  const Formattedresult = formatForGemini(webresults);
  if (!Formattedresult) {
    return { message: "The question was invalid" };
  }


  return Formattedresult;

}